repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.9
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.15.0'  # Use the sha / tag you want to point at
  hooks:
  -   id: mypy

# - repo: local
#   hooks:
#   - id: pytest
#     name: pytest
#     entry: uv run pytest tests
#     language: system
#     types: [python]
#     pass_filenames: false
#     always_run: true
