version: '3.9'

services:
  postgres-test:
    image: postgres:latest
    container_name: anime-tracker-test-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${TEST_POSTGRES_DB}
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_HOST: ${TEST_POSTGRES_HOST}
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
