version: '3.9'

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anime-tracker-main-app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    # expose:
    #   - "8000"
    depends_on:
      - postgres
    # <путь в системе>:<путь в контейнере>
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - .env:/app/.env
      - ./logs:/app/logs
  postgres:
    image: postgres:latest
    container_name: anime-tracker-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data:
