"""add on delete rules"

Revision ID: 9261cb6f5be3
Revises: 8c5e9e7cbf17
Create Date: 2025-03-11 17:26:45.637934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9261cb6f5be3'
down_revision: Union[str, None] = '8c5e9e7cbf17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_rate', ['id'])
    op.drop_constraint('user_rate_user_id_fkey', 'user_rate', type_='foreignkey')
    op.drop_constraint('user_rate_anime_id_fkey', 'user_rate', type_='foreignkey')
    op.create_foreign_key(None, 'user_rate', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_rate', 'anime', ['anime_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_rate', type_='foreignkey')
    op.drop_constraint(None, 'user_rate', type_='foreignkey')
    op.create_foreign_key('user_rate_anime_id_fkey', 'user_rate', 'anime', ['anime_id'], ['id'])
    op.create_foreign_key('user_rate_user_id_fkey', 'user_rate', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_rate', type_='unique')
    # ### end Alembic commands ###
