"""anime model

Revision ID: bedb21a5dd75
Revises: 6e3d9b97d73e
Create Date: 2025-03-04 12:21:24.895574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bedb21a5dd75"
down_revision: Union[str, None] = "6e3d9b97d73e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anime",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("russian", sa.String(), nullable=True),
        sa.Column("english", sa.String(), nullable=True),
        sa.Column("japanese", sa.String(), nullable=True),
        sa.Column("episodes", sa.Integer(), nullable=True),
        sa.Column("episodes_aired", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("poster", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("description_html", sa.String(), nullable=True),
        sa.Column("description_source", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anime")
    # ### end Alembic commands ###
