"""user model

Revision ID: bc3a5e6da1ac
Revises: 
Create Date: 2025-02-18 23:07:46.490749

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bc3a5e6da1ac"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
