name: CI (Test Lint Typecheck)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check with ruff
      uses: astral-sh/ruff-action@v3


  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install the project dependencies
      run: uv sync --all-extras --dev

    - name: Start db in docker
      run: docker compose up postgres -d

    - name: Run tests
      run: uv run pytest tests -s -v




