name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:   

  test:
    runs-on: ubuntu-latest
    env:
      TEST_POSTGRES_DB: db
      TEST_POSTGRES_USER: user
      TEST_POSTGRES_PASSWORD: pass
      TEST_POSTGRES_HOST: localhost
      TEST_POSTGRES_PORT: 5431

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Start test db
      run: docker compose -f docker-compose-test.yaml up -d

    - name: Run tests
      # For example, using `pytest`
      run: uv run pytest tests -s -v

    
    

